services:

  postgres:
    image: postgres:16
    container_name: urlshortener-postgres
    environment:
      POSTGRES_DB: URLShortener
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d URLShortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: urlshortener-app
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/URLShortener
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: